[package]
name = "surge_window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1"
log = "0.4"
wgpu = "0.12"
winit = "0.26"
env_logger = "0.9"